
# Do NOT edit this file. Instead, just call it from the command line,
# using the instructions in the assignment notebook.

import sys
questions = sys.argv[1:]


valid_ids = ['q1', 'q2', 'q3', 'q4']
break_flag = False
invalid_ids = []
for question in questions:
    if question != 'all' and question not in valid_ids:
        invalid_ids.append(question)

if len(invalid_ids) > 0:
    print(str(invalid_ids) + ' is/are not a valid question number(s). The possible question numbers are ' + str(valid_ids) + '.')
    sys.exit()

# Initialize Otter
import otter
grader = otter.Notebook("lab.ipynb")

# %load_ext autoreload
# %autoreload 2

from lab import *

import os
import pandas as pd
import numpy as np
import requests
import bs4
import lxml

# Don't delete this cell!
question1()

if 'q1' in questions or questions == [] or 'all' in questions:
    print(grader.check("q1"))

# don't delete this cell, but do run it -- it is needed for the autograder tests

# public test for extract_book_links 
extract_book_links_fp = os.path.join('data', 'products.html')
extract_book_out = extract_book_links(
    open(extract_book_links_fp, encoding='utf-8').read()
)
extract_book_url = 'scarlet-the-lunar-chronicles-2_218/index.html'

# doc tests for get product info
get_product_info_fp = os.path.join('data', 'Frankenstein.html')
get_product_info_out = get_product_info(
    open(get_product_info_fp, encoding='utf-8').read(), ['Default']
)

# public test for scrape books 
scrape_books_out = scrape_books(1, ['Mystery'])

if 'q2' in questions or questions == [] or 'all' in questions:
    print(grader.check("q2"))

# don't delete this cell, but do run it -- it is needed for the autograder tests

# public test for stock_history
history = stock_history('BYND', 2019, 6)

# public test for stock_stats
stats = stock_stats(history)

if 'q3' in questions or questions == [] or 'all' in questions:
    print(grader.check("q3"))

# don't delete this cell, but do run it -- it is needed for the autograder tests
comments = get_comments(18344932)

if 'q4' in questions or questions == [] or 'all' in questions:
    print(grader.check("q4"))


